; PlatformIO Project Configuration File

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

board_build.partitions = huge_app.csv

monitor_speed = 115200

lib_deps =
    h2zero/NimBLE-Arduino@^1.4.3
    marcoschwartz/LiquidCrystal_I2C